### ISSUE TITLE
Error occurred when training.

### ISSUE THREAD

**Issue by xiaohunshui** [sshaoshuai/MTR#32]
When I ran bash scripts/dist_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 80 --epochs 30 --extra_tag my_first_exp, I met the error below:
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from mtr.models import model as model_utils
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/models/model.py", line 12, in <module>
    from .context_encoder import build_context_encoder
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/models/context_encoder/__init__.py", line 7, in <module>
    from .mtr_encoder import MTREncoder
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/models/context_encoder/mtr_encoder.py", line 12, in <module>
    from mtr.models.utils.transformer import transformer_encoder_layer, position_encoding_utils
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/models/utils/transformer/transformer_encoder_layer.py", line 16, in <module>
    from .multi_head_attention_local import MultiheadAttentionLocal
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/models/utils/transformer/multi_head_attention_local.py", line 21, in <module>
    from mtr.ops import attention
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/ops/attention/__init__.py", line 5, in <module>
    from . import attention_utils
  File "/mnt/sdb/jianghanhu/MTR/tools/../mtr/ops/attention/attention_utils.py", line 9, in <module>
    from . import attention_cuda
ImportError: /mnt/sdb/jianghanhu/MTR/tools/../mtr/ops/attention/attention_cuda.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13193) of binary: /home/jianghanhu/anaconda3/envs/mtr/bin/python
Traceback (most recent call last):
  File "/home/jianghanhu/anaconda3/envs/mtr/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jianghanhu/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jianghanhu/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/jianghanhu/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/jianghanhu/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jianghanhu/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-12_22:11:14
  host      : psdz
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13193)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
.

It is caused by 'from . import attention_cuda' in MTR/tools/../mtr/ops/attention/attention_utils.py, could you please tell me how to solve it?

**Comment by sshaoshuai** [comment]
It seems that the environment is not ready. Have you already compiled the CUDA library by executing 'python setup.py develop'?
