### ISSUE TITLE
err in training

### ISSUE THREAD

**Issue by ieckevinsky** [sshaoshuai/MTR#42]
**Have you encountered the following problem?**
```
torch.cuda.device_count(): 2
Traceback (most recent call last):
  File "train.py", line 217, in main
    model = nn.parallel.DistributedDataParallel(model, device_ids=[0], find_unused_parameters=True)
  File "/root/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 641, in __init__
    main()
  File "train.py", line 217, in main
    model = nn.parallel.DistributedDataParallel(model, device_ids=[0], find_unused_parameters=True)
  File "/root/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 641, in __init__
    dist._verify_params_across_processes(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1646755853042/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:47, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
```
my torch version is 1.11.0,cuda 10.2  gpu rtx 3090
What is your experimental environment? 
thanks

**Comment by sshaoshuai** [comment]
Sorry, I think this error is due to your CUDA environment or GPU status. I have tested this repo under cuda 9.2, 10.2 and PyTorch 1.10+.

**Comment by ieckevinsky** [comment]
thanks a lot , let me try again
