### ISSUE TITLE
Error in eval_one_epoch in the training loop 

### ISSUE THREAD

**Issue by jinning-li** [sshaoshuai/MTR#69]
Hi, I was following the exact same steps in https://github.com/sshaoshuai/MTR/blob/master/docs/TRAIN_EVAL.md to run experiments. The only difference is my experiment was launched by scripts/torchrun_train.sh. 

I keep getting the following error from [`eval_one_epoch()`](https://github.com/sshaoshuai/MTR/blob/a5ba7bdafa09a1a355cc34f8a895499a2b14ddb3/tools/train_utils/train_utils.py#L179) in the training loop after each training epoch is finished:
```
Traceback (most recent call last):
    main()
  File "train.py", line 272, in main  
  File "train.py", line 283, in <module>
    repeat_eval_ckpt(
  File "/home/jinli/mtr/tools/test.py", line 131, in repeat_eval_ckpt
    tb_dict = eval_utils.eval_one_epoch(
  File "/home/jinli/mtr/tools/eval_utils/eval_utils.py", line 66, in eval_one_epoch
    logger.info(f'Total number of samples after merging from multiple GPUs (removing duplicate): {len(pred_dicts)}')
TypeError: object of type 'NoneType' has no len()
    main()
  File "train.py", line 272, in main  
    repeat_eval_ckpt(
  File "/home/jinli/mtr/tools/test.py", line 131, in repeat_eval_ckpt
    tb_dict = eval_utils.eval_one_epoch(
  File "/home/jinli/mtr/tools/eval_utils/eval_utils.py", line 66, in eval_one_epoch
    logger.info(f'Total number of samples after merging from multiple GPUs (removing duplicate): {len(pred_dicts)}')
TypeError: object of type 'NoneType' has no len()
```
I checked inside `eval_one_epoch`. This is because `common_utils.get_dist_info()` returns a nonzero `rank`. But I have no idea how to solve this problem.

Would it be possible if you could provide some insights to it? Thank you very much!

**Comment by jinning-li** [comment]
It turns out the debug code in [this line](https://github.com/sshaoshuai/MTR/blob/a5ba7bdafa09a1a355cc34f8a895499a2b14ddb3/tools/eval_utils/eval_utils.py#L66) needs to be commented out. Everything works fine then.
