### ISSUE TITLE
testing question

### ISSUE THREAD

**Issue by Sally0330** [sshaoshuai/MTR#80]
hello.After I imported requirement.txt and setup.py, the following problems occurred when running train. Could you please answer them? Thank you
Traceback (most recent call last):
  File "F:\MTR-master\tools\train.py", line 23, in <module>
    from mtr.models import model as model_utils
  File "F:\MTR-master\tools\..\mtr\models\model.py", line 15, in <module>
    from mtr.models.context_encoder import build_context_encoder
  File "F:\MTR-master\tools\..\mtr\models\context_encoder\__init__.py", line 7, in <module>
    from .mtr_encoder import MTREncoder
  File "F:\MTR-master\tools\..\mtr\models\context_encoder\mtr_encoder.py", line 12, in <module>
    from mtr.models.utils.transformer import transformer_encoder_layer, position_encoding_utils
  File "F:\MTR-master\tools\..\mtr\models\utils\transformer\transformer_encoder_layer.py", line 16, in <module>
    from .multi_head_attention_local import MultiheadAttentionLocal
  File "F:\MTR-master\tools\..\mtr\models\utils\transformer\multi_head_attention_local.py", line 21, in <module>
    from mtr.ops import attention
  File "F:\MTR-master\tools\..\mtr\ops\attention\__init__.py", line 6, in <module>
    import mtr.ops.attention.attention_utils_v2 as attention_utils_v2
  File "F:\MTR-master\tools\..\mtr\ops\attention\attention_utils_v2.py", line 9, in <module>
    from . import attention_cuda
ImportError: cannot import name 'attention_cuda' from partially initialized module 'mtr.ops.attention' (most likely due to a circular import) (F:\MTR-master\tools\..\mtr\ops\attention\__init__.py)

**Comment by 1832850085** [comment]
you need to run setup.py first:
`python setup.py develop`
