### ISSUE TITLE
data_preprocess.py error

### ISSUE THREAD

**Issue by HaiYangLib** [sshaoshuai/MTR#91]
"""
Traceback (most recent call last):
  File "/home/hy/.conda/envs/open-mmlab/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "data_preprocess.py", line 193, in process_waymo_data_with_scenario_proto
    map_infos = decode_map_features_from_proto(scenario.map_features)
  File "data_preprocess.py", line 135, in decode_map_features_from_proto
    raise ValueError
ValueError
"""

scenario.map_features
map_features only has id

**Comment by wind-bell999** [comment]
The new dataset has added categories to the map, which can cause errors.
in File "/data/dht/simcopilot/MTR/mtr/datasets/waymo/data_preprocess.py"
Adding continue after the else: on line 133 can solve the problem.

**Comment by leandro-svg** [comment]
map_infos = {
    'lane': [],
    'road_line': [],
    'road_edge': [],
    'stop_sign': [],
    'crosswalk': [],
    'speed_bump': [],
    'driveway': []  # <-- add this
}

elif cur_data.HasField('driveway'):
            global_type = polyline_type.get('TYPE_DRIVEWAY', 0)  # Use 0 or add to your polyline_type dict
            cur_polyline = np.stack([np.array([point.x, point.y, point.z, global_type]) for point in cur_data.driveway.polygon], axis=0)
            cur_polyline_dir = get_polyline_dir(cur_polyline[:, 0:3])
            cur_polyline = np.concatenate((cur_polyline[:, 0:3], cur_polyline_dir, cur_polyline[:, 3:]), axis=-1)
            map_infos['driveway'].append(cur_info)
